version: "2"
services:
  REST:
    image: blkio10/explorer-free:2.1.2
    container_name: blk-free-explorer
    ports:
      - 8081:8081
    environment:
      - ENABLE_PRIVATE_QUORUM=enabled
      - JAVA_OPTS=
      - EXPLORER_PORT=8081
      - NODE_ENDPOINT=${NODE_ENDPOINT}
      - MONGO_CLIENT_URI=mongodb://mongodb:27017
      - MONGO_DB_NAME=test
      - UI_IP=http://localhost:5000
      - USE_COSMOS=false
    depends_on:
      - mongodb

  mongodb:
    image: mongo:3.4.10
    container_name: blk-free-mongodb
    ports:
      - 27017:27017
    entrypoint: mongod --smallfiles --logpath=/dev/null --bind_ip "0.0.0.0"

  web:
    image: blkio10/explorer-ui-free:2.1.2
    container_name: blk-free-explorer-ui
    ports:
      - 5000:5000
    environment:
      - REACT_APP_EXPLORER=http://localhost:8081