test:
  name: simple
  description: benchmark for besu
  clients:
    type: local
    number: 1
  rounds:
    - label: open
      txNumber:
        - 5000
      rateControl:
        - type: fixed-rate
          opts:
            tps: 100
        - type: fixed-rate
          opts:
            tps: 200
        - type: fixed-rate
          opts:
            tps: 300
      arguments:
        money: 10000
      callback: benchmark/simple/open.js
monitor:
  type:
    - docker
  docker:
    name:
      - http://$BESU1_SERVICE0_BESU_NETWORK:2375
  interval: 1